### ISSUE TITLE
STRM builder - specialize for Emby

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/Python-GoogleDrive-VideoStream#38]

**Comment by maximilianh75** [comment]
Any news about that feature???

**Comment by ddurdle** [comment]
Is there a particular aspect you are waiting for?

I've been working on this daily.  If there is a particular aspect you are requesting let me know.

![screenshot at 2018-03-03 08-16-15](https://user-images.githubusercontent.com/851508/36934675-5e878490-1ebb-11e8-8db1-c4c859836a70.png)

**Comment by maximilianh75** [comment]
I'm curious about if it possible to generate strm files that's allow transcoded gdrive in client aspect.
What i say it's because google makes a hash linked to ip adress and other ip adress can't open.
It's any command in googles drive api to generate a hash ip for the cliente ip at a server level????
the second question it's about photos, it's possible integrate to emby in some aspect??? Have photo galleries and slideshows
The third question it's about if it possible or if you know how to write the emby DB for music 
Music not recognize streams files and not write metadata, because read only directly to music files . Emby use ffmpeg to decode the music and read the internal metadata of music and not allow nfo files
Maybe you can get some way to add this metadata of music db or music brainz directly to DB file

**Comment by ddurdle** [comment]
music strm is not supported by emby

**Comment by maximilianh75** [comment]
Yes I know but you can add music strms manually, the idea if u can add sort kind of tool to your app to communicate to emby DB and add this data to DB directly

**Comment by ddurdle** [comment]
completed.
