### ISSUE TITLE
No metadata in Emby

### ISSUE THREAD

**Issue by Thomvh** [ddurdle/Python-GoogleDrive-VideoStream#65]
Once the strm files are created and scanned. The libary only show the names.
![image](https://user-images.githubusercontent.com/1483055/41046640-06956a00-69ab-11e8-82ba-6c02ebffe88e.png)

**Comment by ddurdle** [comment]
Are you exporting with catalog = true option?

When you add the tv and movies folder to emby, are you selecting "tv shows" and "Movies"?

**Comment by Thomvh** [comment]
Yes, I exported with catalog=true and I selected the movie folder with
Movies as type.

Op wo 6 jun. 2018 18:50 schreef ddurdle <notifications@github.com>:

**Comment by ddurdle** [comment]
From your screenshots, it looks like it is identifying the files correctly (title and year) but not downloading the nfo and artwork.

Some things to check:
1) the STRM folder you create and use, make sure emby user has access to write to it -- is this Windows or Linux?  I set umask 022 and then I set the sticky bit on the folder (sudo chmod 1775 -R /path/folder).  I then chown myuser:emby -R /path/folder so that the group emby is added as group owner of the files.  This ensures that emby can write to the folder (such as for storing thumbnails)
2) I suggest enable these four things on the folder in emby (unchecked by default)  -- edit the library folder settings:
![screenshot at 2018-06-06 14-15-29](https://user-images.githubusercontent.com/851508/41057118-38ccff72-6994-11e8-8234-727027f4782d.png)
![screenshot at 2018-06-06 14-16-52](https://user-images.githubusercontent.com/851508/41057147-4ee8a284-6994-11e8-9a72-72ed8c2e40e3.png)
![screenshot at 2018-06-06 14-17-28](https://user-images.githubusercontent.com/851508/41057168-5efb8b28-6994-11e8-94f3-a167b704a7cc.png)

**Comment by Thomvh** [comment]
No it's not identifying correctly. The file names are the names that VideoStream creates. When I click on identify it find nothing. Which is the weird part? Matched your settings. This doesn't solve it. Unfortunately!

**Comment by ddurdle** [comment]
Which version of emby are you running?  You might want to post int he emby forum as if it is the latest build, it may be newly introduced bug.  I stay on emby 3.3.1.12 just to avoid chaos of new "features"  cough... bugs... that pop up by updating daily.

**Comment by Thomvh** [comment]
https://emby.media/community/index.php?/topic/59702-after-todays-docker-update-can%C2%B4t-add-any-data/

Maybe you are right! XD But while testing this I ran into the problem. That VideoStream won't start anymore. Because of the adres being in use. Whilst I didn't ran anything else on that port...

**Comment by ddurdle** [comment]
It may not have been stopped correctly.  It is safe to kill -9 or CTRL-C on the proces most of the time, but sometimes if there is a scheduled job still running or something actively streaming over it, it won't exit because it is being used.  In that case, you can look for the process and kill it (ps -ef | grep "python default.py".

To gracefully invoke stop, you can hit http://IP:9988/kill  which will give it the kill signal to shutdown when all connections and scheduled jobs have completed.
