### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by Kraevin** [ddurdle/Python-GoogleDrive-VideoStream#93]
The script itself seems to work great one everything except for the scheduler. No matter what i do, it says it creates it and will activate in 60 seconds, but doesn't seem to start. I have tried forcing a start on it, doing a reset. And going back several versions and none seem to start the scheduler. Not for sure if i am missing something here.

Also not for sure if this has something to do with it, clicking on the scheduled task itself gives a page not found error. I have included some images.

![3](https://user-images.githubusercontent.com/29154031/45295053-68897600-b4cb-11e8-8413-fcf98de3d9f4.PNG)
![1](https://user-images.githubusercontent.com/29154031/45295056-6a533980-b4cb-11e8-882c-057066e09a25.PNG)
![2](https://user-images.githubusercontent.com/29154031/45295061-6cb59380-b4cb-11e8-8a6e-d22a41586664.PNG)
![4](https://user-images.githubusercontent.com/29154031/45295063-6de6c080-b4cb-11e8-991e-6f60284ba7ca.PNG)

I can manually go in and save the strm files and they save fine, just for some reason the scheduler isnt working at all.

**Comment by ddurdle** [comment]
The scheduler logic checks every 60 seconds if there is a scheduled task to run.  On a bunch of servers I use for production users (where I have a lot of scheduled jobs -- 75  and I add /remove regularly), I have not run into the issue.  In some test boxes where there is less usage (such as only 1 or 2 jobs) and not many users, I have noticed it seemed to take "longer" to kick off (as in I didn't see it kick off within 5 mins).  For these new jobs, I'd restart the plugin which will force the job to run at startup since it is marked ready to start.

I believe the issue might be more around the DBM and caching.  That the database writes to schedule the call are not being picked up by the scheduler -- the scheduler has cached a value and isn't picking up that it has changed, or I do a scan looking for scheduled jobs and it only sees the jobs that existed from the prior scans and not the newly added ones.

Still looking at different options to make it universally work.

**Comment by Kraevin** [comment]
Thank you for the quick reply ddurdle!

Is there something i am doing wrong then? I have tested this by even adding new movies for it to scan in, and nothing. Should it also being giving the page isn't working no response when clicking on a scheduled task? Just want to make sure i am not missing something or doing something wrong.

**Comment by ddurdle** [comment]
Clicking the job isn't actually going to resolve to anything, so that is expected.

So, the initial sync via scheduler finishes with X STRM files (Change tracking=), then when you keep monitoring, does the change tracking number increase?

Also, is the source location a team drive or non-team drive?

**Comment by Kraevin** [comment]
Doing a manual save or the strm files and not using the schedule. i get this..

![5](https://user-images.githubusercontent.com/29154031/45324599-98ad3500-b51c-11e8-9fa6-c36f6e448092.PNG)

doing a scheduled task, i never even get that.
The first time i get 
![1](https://user-images.githubusercontent.com/29154031/45324666-cbefc400-b51c-11e8-8a0e-2ab83e1b52c0.PNG)

then if i try and restart the task, using reset then restarting the script, or doing force start i get a blank page.

![6](https://user-images.githubusercontent.com/29154031/45324794-34d73c00-b51d-11e8-9f46-af543e124298.PNG)

Here is the command window if that helps, edited out the ip's

![7](https://user-images.githubusercontent.com/29154031/45324807-3e60a400-b51d-11e8-96a1-cd8b570a3752.PNG)

**Comment by Kraevin** [comment]
Do you have discord or another method i can send you the images without having to edit out the ip's , DDurdle? Might be a little easier.

**Comment by ddurdle** [comment]
discord is here -> https://discord.gg/ZuDC3q

You'll see me on the owner list, same username as here.

**Comment by Kraevin** [comment]
Thank you, sent you a message on discord.
